const { v4: uuid } = require("uuid");
const { getJson, setJson } = require("./tenant-module.mysql");
const presets = require("../catering-presets.repository");
const MODULE_KEY='catering-events';
function isLegacyEvent(e){ return e && !e.sections && (e.customer!=null || e.people!=null || e.price!=null); }
function deepCopySections(sections){ return (sections||[]).map((s)=>({ id:uuid(), name:String(s.name||'').trim()||'Sezione', type: presets.SECTION_TYPES.includes(s.type)?s.type:'custom', items:(s.items||[]).map((i)=>({ id:uuid(), name:String(i.name||'').trim()||'Voce', mode: presets.ITEM_MODES.includes(i.mode)?i.mode:'priced', quantityPerPerson:i.mode==='detailed'?Number(i.quantityPerPerson)||0:null, unit:i.mode==='detailed'?(i.unit||'g'):null, pricePerPerson:i.mode==='priced'?Number(i.pricePerPerson)||0:null, fixedPrice:i.mode==='priced'?Number(i.fixedPrice)||0:null, recipeId:i.recipeId||null, notes:String(i.notes||'').trim() })) })); }
function migrateLegacyToFull(legacy){ return { id:legacy.id||uuid(), restaurantId:null, title:String(legacy.customer||'').trim()||'Evento', eventName:String(legacy.customer||'').trim()||'Evento', clientName:String(legacy.customer||'').trim()||'', eventDate:legacy.date||'', guestCount:Number(legacy.people)||0, menuType:'custom', presetMenuId:null, sections:[], notes:String(legacy.note||'').trim(), pricePerPerson:legacy.price&&legacy.people?Number(legacy.price)/Number(legacy.people):0, totalEstimatedPrice:Number(legacy.price)||0, status:'draft', createdAt:legacy.createdAt||new Date().toISOString(), updatedAt:legacy.updatedAt||new Date().toISOString(), customer:legacy.customer,date:legacy.date,people:legacy.people,price:legacy.price,note:legacy.note }; }
function normalizeEvent(e){ if(isLegacyEvent(e)) return migrateLegacyToFull(e); const sections=Array.isArray(e.sections)?deepCopySections(e.sections):[]; return { id:e.id||uuid(), restaurantId:e.restaurantId||null, title:String(e.title||e.eventName||'').trim()||'Evento', eventName:String(e.eventName||e.title||'').trim()||'Evento', clientName:String(e.clientName||e.customer||'').trim(), eventDate:e.eventDate||e.date||'', guestCount:Number(e.guestCount??e.people)||0, menuType:String(e.menuType||'custom').trim(), presetMenuId:e.presetMenuId||null, sections, notes:String(e.notes||e.note||'').trim(), pricePerPerson:Number(e.pricePerPerson)||0, totalEstimatedPrice:Number(e.totalEstimatedPrice)||0, status:String(e.status||'draft').trim(), createdAt:e.createdAt||new Date().toISOString(), updatedAt:e.updatedAt||new Date().toISOString(), customer:e.clientName||e.customer, date:e.eventDate||e.date, people:e.guestCount??e.people, price:e.totalEstimatedPrice??e.price, note:e.notes||e.note }; }
async function readAll(){ const data=await getJson(MODULE_KEY,[]); const list=Array.isArray(data)?data:(data&&Array.isArray(data.events)?data.events:[]); return list.map(normalizeEvent); }
async function writeAll(events){ await setJson(MODULE_KEY, events); }
async function getAll(){ return readAll(); }
async function getById(id){ const list=await readAll(); return list.find((e)=>e.id===id)||null; }
async function create(data){ const event=normalizeEvent({ ...data,id:data.id||uuid() }); const list=await readAll(); list.push(event); await writeAll(list); return event; }
async function update(id,data){ const list=await readAll(); const idx=list.findIndex((e)=>e.id===id); if(idx===-1) return null; const next=normalizeEvent({ ...list[idx], ...data, id:list[idx].id, updatedAt:new Date().toISOString() }); list[idx]=next; await writeAll(list); return next; }
async function remove(id){ const list=await readAll(); const idx=list.findIndex((e)=>e.id===id); if(idx===-1) return false; list.splice(idx,1); await writeAll(list); return true; }
async function createFromPreset(presetId, overrides={}){ const preset=await presets.getById(presetId); if(!preset) return null; const base={ title: overrides.title || preset.name || 'Evento catering', eventName: overrides.eventName || overrides.title || preset.name || 'Evento catering', clientName: overrides.clientName || '', eventDate: overrides.eventDate || '', guestCount: Number(overrides.guestCount) || 0, menuType:'preset', presetMenuId:preset.id, sections: deepCopySections(preset.sections), notes: overrides.notes || preset.notes || '', pricePerPerson: Number(overrides.pricePerPerson ?? preset.defaultPricePerPerson) || 0, totalEstimatedPrice: Number(overrides.totalEstimatedPrice) || 0, status: overrides.status || 'draft' }; return create(base); }
module.exports={ getAll,getById,create,update,remove,createFromPreset };
