const { getJson, setJson } = require("./tenant-module.mysql");
const CATEGORIES = ["antipasto","primo","secondo","contorno","dolce","bevanda","extra"];
const MODULE_KEY = "daily-menu";
async function readData(){ const raw=await getJson(MODULE_KEY,null); if(raw&&typeof raw==='object') return raw; return { menuActive:false, updatedAt:null, dishes:[] }; }
async function writeData(data){ const d={ menuActive:data.menuActive!==false, updatedAt:new Date().toISOString(), dishes:Array.isArray(data.dishes)?data.dishes:[] }; await setJson(MODULE_KEY,d); return d; }
function getNextId(dishes){ const ids=dishes.map((d)=>d.id).filter((n)=>Number.isFinite(n)); return ids.length?Math.max(...ids)+1:1; }
async function getAll(){ return readData(); }
async function getActiveDishes(){ const data=await readData(); if(!data.menuActive) return []; return (data.dishes||[]).filter((d)=>d.active!==false); }
async function addDish(dish){ const data=await readData(); const dishes=data.dishes||[]; const id=getNextId(dishes); const cat=String(dish.category||'extra').toLowerCase(); const category=CATEGORIES.includes(cat)?cat:'extra'; const newDish={ id,name:String(dish.name||'').trim()||'Senza nome',description:String(dish.description||'').trim()||'',category,price:Number(dish.price)||0,active:dish.active!==false,allergens:String(dish.allergens||'').trim()||'',order:dishes.length,recipeId:dish.recipeId||dish.recipe_id||null }; dishes.push(newDish); await writeData({ ...data,dishes }); return newDish; }
async function updateDish(id,updates){ const data=await readData(); const dishes=data.dishes||[]; const idx=dishes.findIndex((d)=>String(d.id)===String(id)); if(idx===-1) return null; const cat=updates.category!=null?String(updates.category).toLowerCase():null; const patch={}; if(updates.name!==undefined) patch.name=String(updates.name).trim()||dishes[idx].name; if(updates.description!==undefined) patch.description=String(updates.description).trim(); if(updates.category!==undefined) patch.category=CATEGORIES.includes(cat)?cat:dishes[idx].category; if(updates.price!==undefined) patch.price=Number(updates.price)||0; if(updates.active!==undefined) patch.active=!!updates.active; if(updates.allergens!==undefined) patch.allergens=String(updates.allergens).trim(); if(updates.recipeId!==undefined) patch.recipeId=updates.recipeId||null; if(updates.recipe_id!==undefined) patch.recipeId=updates.recipe_id||null; dishes[idx]={...dishes[idx],...patch}; await writeData({ ...data,dishes }); return dishes[idx]; }
async function removeDish(id){ const data=await readData(); const dishes=data.dishes||[]; const idx=dishes.findIndex((d)=>String(d.id)===String(id)); if(idx===-1) return false; dishes.splice(idx,1); await writeData({ ...data,dishes }); return true; }
async function toggleDish(id){ const data=await readData(); const dishes=data.dishes||[]; const idx=dishes.findIndex((d)=>String(d.id)===String(id)); if(idx===-1) return null; dishes[idx].active=!dishes[idx].active; await writeData({ ...data,dishes }); return dishes[idx]; }
async function setMenuActive(active){ const data=await readData(); data.menuActive=!!active; await writeData(data); return data; }
module.exports={ CATEGORIES,getAll,getActiveDishes,addDish,updateDish,removeDish,toggleDish,setMenuActive };
