const crypto = require("crypto");
const { getJson, setJson } = require("./tenant-module.mysql");
const MODULE_KEY = "staff-shifts";
function createId(){ if(crypto.randomUUID) return crypto.randomUUID(); return `sh_${Date.now()}_${Math.floor(Math.random()*10000)}`; }
async function readAllShifts(){ const data=await getJson(MODULE_KEY, []); if(Array.isArray(data)) return data; if(data && typeof data==='object' && data.id) return [{...data,id:data.id||createId()}]; return []; }
async function writeAllShifts(shifts){ await setJson(MODULE_KEY, Array.isArray(shifts)?shifts:[]); }
const getAll = readAllShifts;
async function getByStaffId(staffId,filters={}){ let shifts=await readAllShifts(); shifts=shifts.filter((s)=>s.staffId===staffId); if(filters.dateFrom) shifts=shifts.filter((s)=>(s.date||'')>=filters.dateFrom); if(filters.dateTo) shifts=shifts.filter((s)=>(s.date||'')<=filters.dateTo); if(filters.status) shifts=shifts.filter((s)=>(s.status||'scheduled')===filters.status); return shifts.sort((a,b)=>(a.date||'').localeCompare(b.date||'')||0); }
async function getByDateRange(dateFrom,dateTo,filters={}){ let shifts=await readAllShifts(); if(dateFrom) shifts=shifts.filter((s)=>(s.date||'')>=dateFrom); if(dateTo) shifts=shifts.filter((s)=>(s.date||'')<=dateTo); if(filters.staffId) shifts=shifts.filter((s)=>s.staffId===filters.staffId); if(filters.department) shifts=shifts.filter((s)=>s.area===filters.department||s.department===filters.department); return shifts.sort((a,b)=>(a.date||'').localeCompare(b.date||'')); }
async function getById(id){ const shifts=await readAllShifts(); return shifts.find((s)=>s.id===id)||null; }
async function create(data){ const shifts=await readAllShifts(); const shift={ id:data.id||createId(), staffId:data.staffId||'', date:data.date||'', start:data.start||'', end:data.end||'', area:data.area||data.department||'', department:data.department||data.area||'', status:data.status||'scheduled', type:data.type||'work', notes:data.notes||'', createdAt:data.createdAt||new Date().toISOString()}; shifts.push(shift); await writeAllShifts(shifts); return shift; }
async function createMany(items){ const shifts=await readAllShifts(); const created=[]; for(const data of items){ const shift={ id:data.id||createId(), staffId:data.staffId||'', date:data.date||'', start:data.start||'', end:data.end||'', area:data.area||data.department||'', department:data.department||data.area||'', status:data.status||'scheduled', type:data.type||'work', notes:data.notes||'', createdAt:data.createdAt||new Date().toISOString()}; shifts.push(shift); created.push(shift);} await writeAllShifts(shifts); return created; }
async function update(id,data){ const shifts=await readAllShifts(); const idx=shifts.findIndex((s)=>s.id===id); if(idx===-1) return null; for(const k of ['date','start','end','area','department','status','type','notes']) if(data[k]!==undefined) shifts[idx][k]=data[k]; await writeAllShifts(shifts); return shifts[idx]; }
async function remove(id){ const shifts=await readAllShifts(); const idx=shifts.findIndex((s)=>s.id===id); if(idx===-1) return false; shifts.splice(idx,1); await writeAllShifts(shifts); return true; }
module.exports={ getAll,getByStaffId,getByDateRange,getById,create,createMany,update,remove };
